name: Lint and format

on: [push, pull_request]

jobs:

  run-linters:
    permissions:
      contents: write

    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm install


      - name: identification
        run: |
           git config --global user.email "khadijaaws21@gmail.com"
           git config --global user.name "khadija-AC"

      - name: conventionel commit
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional, for private repositories.
          allowed-commit-types: "feat,fix" # Optional, set if you want a subset of commit types to be allowed.

 

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          auto_fix: true
    
      - name: Verification(cat index.js)
        run: cat index.js

     