name: Lint and format

on: [push, pull_request]

jobs:

  run-linters:
    permissions:
      contents: write

    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm install


      - name: identification
        run: |
           git config --global user.email "khadijaaws21@gmail.com"
           git config --global user.name "khadija-AC"

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
         eslint: true
         prettier: true

      - name: Run ESLint with fix
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --fix

      - name: Commit changes if any
        run: |
            git config --global user.email "khadijaaws21@gmail.com"
            git config --global user.name "khadija-AC"
            if [ -n "$(git status --porcelain)" ]; then
              git add .
              git commit -m "chore: fix linting issues"
              git push
            fi
      - name: Check commit messages
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            base_sha="${{ github.event.pull_request.base.sha }}"
          else
            base_sha="${{ github.event.before }}"
          fi
          commits=$(git log --format=%B ${base_sha}..${{ github.sha }})
          echo "$commits" | npx commitlint
          

      
    
     