name: version
on:
    push:
      branches:
        - main
    workflow_dispatch:


jobs:
     version:
       name: Gestion Versions
       runs-on: ubuntu-latest
       steps:

        - name: Trigger linting workflow
          uses: actions/github-script@v6
          with:
           script: |
             const { github, context } = require('@actions/github');
             await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'linting.yml',
              ref: context.ref,
             });
           
        
        - name: Check out Git repository
          uses: actions/checkout@v3

        - name: workflows
          run: cat ./.github/workflows/linting.yml 
          

        - name: Set up Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 20
     
        - name: identification
          run: |
             git config --global user.email "khadijaaws21@gmail.com"
             git config --global user.name "khadija-AC"

        - name: execute standard-version
          run: npx standard-version

        - name: push changes
          run: git push --follow-tags origin main && npm publish