name: version
on:
    push:
     branches:
      - main

jobs:

    version:
       name: Gestion Version
       runs-on: self-hosted
       steps:

        - name: Check out Git repository
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 20
     
        - name: identification
          run: |
             git config --global user.email "khadijaaws21@gmail.com"
             git config --global user.name "khadija-AC"

        - name: execute standard-version
          run: npx standard-version

        - name: push changes
          run: git push --follow-tags origin main 
